### ISSUE TITLE
Cannot compile with conda build

### ISSUE THREAD

**Issue by kejang** [pybind/python_example#106]
Hello all, 

I'm getting the attached errors when I run `conda build`.

# Demo
```bash
conda create -n bug_report python=3.8
conda activate bug_report
git clone https://github.com/pybind/python_example.git
cd python_example/conda.recipe
conda build .
```

# Error message on Linux (Fedora 35)
```bash
Successfully built python-example
Installing collected packages: python-example

Successfully installed python-example-0.0.1
Removed build tracker: '/tmp/pip-req-tracker-zcetdlyw'

Resource usage statistics from building python_example:
   Process count: 6
   CPU time: Sys=0:00:00.2, User=0:00:02.4
   Memory: 340.8M
   Disk usage: 392B
   Time elapsed: 0:00:06.1


Packaging python_example
INFO:conda_build.build:Packaging python_example
Packaging python_example-0.0.1-py38h2bc3f7f_0
INFO:conda_build.build:Packaging python_example-0.0.1-py38h2bc3f7f_0
number of files: 9
Warning: rpath /home/kejang/anaconda3/conda-bld/python_example_1655696142146/_build_env/lib is outside prefix /home/kejang/anaconda3/conda-bld/python_example_1655696142146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh (removing it)
Traceback (most recent call last):
  File "/home/kejang/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 2351, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 1644, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/build.py", line 1490, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/post.py", line 1317, in post_build
    check_overlinking(m, files, host_prefix)
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/post.py", line 1223, in check_overlinking
    return check_overlinking_impl(m.get_value('package/name'),
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/post.py", line 1047, in check_overlinking_impl
    packages = dists_from_names(requirements_run, run_prefix)
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/post.py", line 638, in dists_from_names
    pkgs = linked_data_no_multichannels(prefix)
  File "/home/kejang/anaconda3/lib/python3.8/site-packages/conda_build/utils.py", line 2070, in linked_data_no_multichannels
    from conda.common.compat import itervalues
ImportError: cannot import name 'itervalues' from 'conda.common.compat' (/home/kejang/anaconda3/lib/python3.8/site-packages/conda/common/compat.py)
```
# Error message on macOS (12.4 (Monterey))
```bash
error: command '/Users/kejang/opt/anaconda3/conda-bld/python_example_1655695965393/_build_env/bin/x86_64-apple-darwin13.4.0-clang++' failed with exit code 1
  Building wheel for python-example (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for python-example
Failed to build python-example
ERROR: Could not build wheels for python-example which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 357, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for python-example which use PEP 517 and cannot be installed directly
Removed build tracker: '/private/tmp/pip-req-tracker-432e3be0'
Traceback (most recent call last):
  File "/Users/kejang/opt/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 2211, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/kejang/opt/anaconda3/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/kejang/opt/anaconda3/conda-bld/python_example_1655695965393/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by c-dickens** [comment]
Hello @kejang, did you manage to resolve this issue? I seem to be having the same problem and don't know how to rectify it.
