### ISSUE TITLE
pip.req : No Module Found error

### ISSUE THREAD

**Issue by ugurkanates** [pybind/python_example#56]
Hi , I believe this is related to  
https://stackoverflow.com/questions/25192794/no-module-named-pip-req
PIP version but still its an going error. 
pip install pybind

Python 3.7.3
pip 20.0.2
gcc 7.5.0 ubuntu 18.04

```
 ERROR: Command errored out with exit status 1:
     command: /home/paypaytr/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u0ane2tw/pyangbind-brcd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u0ane2tw/pyangbind-brcd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-u0ane2tw/pyangbind-brcd/pip-egg-info
         cwd: /tmp/pip-install-u0ane2tw/pyangbind-brcd/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u0ane2tw/pyangbind-brcd/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ugurkanates** [comment]
sorry error was due to pybind not pybind11 and wrong repo
